export const GET_EMPLEADOS = 'GET_EMPLEADOS'
export const NUEVO_EMPLEADO = 'NUEVO_EMPLEADO'
export const GUARDAR_EMPLEADO = 'GUARDAR_EMPLEADO'

export const GET_SOLICITUDES = 'GET_SOLICITUDES'
export const NUEVA_SOLICITUD = 'NUEVA_SOLICITUD'
export const GUARDAR_SOLICITUD = 'GUARDAR_SOLICITUD'